const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{window.firebase={apps:[{}],auth:()=>({currentUser:{getIdToken:async()=> 'test-token'},onAuthStateChanged:()=>{}})};localStorage.setItem('lyrad_session',JSON.stringify({uid:'LYR-1'}));});
const product={id:'11111111-1111-4111-8111-111111111111',owner_id:'test',name:"Tool 'special' <script>alert(1)</script>",seller_name:'Nhà phát hành',description:'Ứng dụng dành cho máy tính',platform:'windows',category:'app',kind:'sale',price:59000,payment_method:'Chuyển khoản ngân hàng',contact:'seller@example.com',filename:'tool.exe',file_size:2048,sha256:'a'.repeat(64),status:'approved',return_count:0,review_note:'',created_at:new Date().toISOString()};
await page.route('**/*',async route=>{const url=new URL(route.request().url());if(url.hostname!=='localhost')return route.fulfill({body:'',contentType:'application/javascript'});if(url.pathname==='/api/data')return route.fulfill({json:[{db_key:'lyrad_real_users',db_data:[]}]});if(url.pathname==='/api/market/me')return route.fulfill({json:{role:'USER'}});if(url.pathname==='/api/market/products')return route.fulfill({json:[product,{...product,id:'22222222-2222-4222-8222-222222222222',kind:'catalog'}]});if(url.pathname==='/api/market/mine')return route.fulfill({json:[{...product,status:'returned',return_count:1,review_note:'Sửa mô tả'}]});if(url.pathname==='/api/market/review')return route.fulfill({json:[{...product,status:'pending'}]});if(url.pathname==='/api/market/history')return route.fulfill({json:[]});if(url.pathname.startsWith('/api/'))return route.fulfill({json:[]});return route.continue();});
await page.goto('http://localhost:3000');await page.waitForFunction(()=>typeof market!=='undefined');await page.waitForTimeout(300);await page.getByRole('tab',{name:'Máy Tính (PC)',exact:true}).first().click();assert.equal(await page.locator('#view-explore .app-card').count(),1);await page.getByRole('tab',{name:'Mobile (PE)',exact:true}).first().click();assert.equal(await page.locator('#view-explore .app-card').count(),0);
await page.locator('.nav-links a').filter({hasText:'Đăng Bán Sản Phẩm'}).click();await page.locator('#sale-name').waitFor();await page.locator('#sale-platform').selectOption('windows');assert.equal(await page.locator('#sale-file').getAttribute('accept'),'.exe,.zip,.rar,.7z');await page.getByRole('tab',{name:'Bài đăng của tôi',exact:true}).click();await page.getByRole('button',{name:'Sửa & gửi lại'}).click();assert.equal(await page.locator('#sale-file').getAttribute('required'),null);await page.screenshot({path:'../../sales-desktop.png',fullPage:true});
await page.locator('.nav-links a').filter({hasText:'Kiểm Duyệt Sản Phẩm'}).click();await page.locator('#review-key').fill('test-key');await page.getByRole('button',{name:'Mở khóa',exact:true}).click();await page.getByRole('button',{name:'Trả về sửa (1 lần)'}).waitFor();await page.screenshot({path:'../../review-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});await page.locator('.nav-links a').filter({hasText:'Đăng Bán Sản Phẩm'}).click();await page.locator('#sale-name').waitFor();await page.screenshot({path:'../../sales-mobile.png',fullPage:true});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false,'mobile horizontal overflow');assert.deepEqual(errors,[]);console.log('Browser: PE/PC filters, sale edit, EXE accept, review unlock, mobile layout passed');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
